CREATE DATABASE NHOM_52;
USE NHOM_52;

-- B?ng HOADON
CREATE TABLE HOADON (
    MaDBH CHAR(4) NOT NULL PRIMARY KEY,
    NgayBH DATE NOT NULL,
    MaCQT NVARCHAR(50) NOT NULL,
    GiamGia DECIMAL(18, 2),
    TongTien AS (
        ISNULL((SELECT SUM(ThanhTien) 
                FROM HOADONCHITIET 
                WHERE HOADONCHITIET.MaDBH = HOADON.MaDBH), 0) 
        - ISNULL(GiamGia, 0)
    ) PERSISTED,
    HTTT NVARCHAR(50)
);

-- B?ng KHACHHANG
CREATE TABLE KHACHHANG (
    MaID VARCHAR(12) NOT NULL,
    TenKH NVARCHAR(50) NOT NULL,
    MaDBH CHAR(4) NOT NULL,
    MST NVARCHAR(50),
    DiaChiKH NVARCHAR(100),
    STKKH VARCHAR(20),
    SDTKH CHAR(10) CHECK (LEN(SDTKH) = 10),
    PRIMARY KEY (MaID, MaDBH),
    FOREIGN KEY (MaDBH) REFERENCES HOADON(MaDBH)
);

-- B?ng NHANVIEN
CREATE TABLE NHANVIEN (
    MaNV VARCHAR(10) NOT NULL PRIMARY KEY,
    TenNV NVARCHAR(100) NOT NULL,
    ChucVu NVARCHAR(100),
    MaDBH CHAR(4) NOT NULL,
    FOREIGN KEY (MaDBH) REFERENCES HOADON(MaDBH)
);

-- B?ng SANPHAM
CREATE TABLE SANPHAM (
    MaSP VARCHAR(10) NOT NULL PRIMARY KEY,
    TenSP NVARCHAR(100) NOT NULL,
    DVT VARCHAR(10) NOT NULL,
    DonGia DECIMAL(18, 2) NOT NULL
);

-- B?ng LOAIHANG
CREATE TABLE LOAIHANG (
    MaLoai VARCHAR(5) NOT NULL,
    MaSP VARCHAR(10) NOT NULL,
    TenLH NVARCHAR(50),
    PRIMARY KEY (MaLoai, MaSP),
    FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);

-- B?ng HOADONCHITIET
CREATE TABLE HOADONCHITIET (
    MaSP VARCHAR(10) NOT NULL,
    MaDBH CHAR(4) NOT NULL,
    PRIMARY KEY (MaSP, MaDBH),
    SoLuong FLOAT NOT NULL,
    ThanhTien AS (SoLuong * (SELECT DonGia FROM SANPHAM WHERE SANPHAM.MaSP = HOADONCHITIET.MaSP)) PERSISTED,
    FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP),
    FOREIGN KEY (MaDBH) REFERENCES HOADON(MaDBH)
);